#+title: gptel-agent

Agentic use mode for gptel: This is a collection of tools and prompts for
gptel to enable easy agentic LLM use.

How to use:

- Set =gptel-model= and =gptel-backend= to use your preferred LLM.

- Run M-x =gptel-agent=.  This will open a buffer with the agent preset
  loaded.

- Use gptel as usual, calling =gptel-send= etc.

- If you change the system prompt, tools or other settings in this buffer, you
  can reset the agent state by (re)applying the "gptel-agent" preset from
  gptel's menu.

- As with gptel, you can use gptel-agent in any buffer.  Just apply the
  "gptel-agent" preset in the buffer first.

gptel-agent can delegate tasks to "sub-agents".  Sub-agents can be specified in
Markdown or Org files in a directory.  To see how to specify agents, examine the
"agents" directory in this package.  You can add your directory of agents to
=gptel-agent-dirs=, which see.

In this demo, gptel-agent delegates a research task to two agents, who perform
it in parallel and generate reports that gptel-agent uses to answer the question:

https://github.com/user-attachments/assets/03585600-3bb9-4bf7-b5c8-7e02a28c7a37

Right now there are only two sub-agents: =researcher= and =introspector=.  You
can ask the LLM to delegate a task to them.

Highly recommended: Get the [[https://github.com/positron_solutions/ragmacs][ragmacs tools]] if you plan to use gptel-agent for
anything Emacs related, as the =introspector= agent requires these tools and
will throw an error otherwise.

Please note: gptel-agent uses significantly more tokens than the average
gptel LLM interaction.
